language: java

dist: bionic
sudo: required

jdk:
  - openjdk8

addons:
  apt:
    packages:
      - libaio-dev
      - libdbus-glib-1-dev
      - xsltproc
  sonarcloud:
    organization: "aplex"
    token:
      secure: "w77jzXGLysjsdrT20DPMBnWn4X4/Kwkx0o5ms6deYICKGn/SYD+PfKLm6GZmcUPCMVWD0cyrKR+fygzykJ7lOxIYGJnyg6ASkT1cmK22TgUCjXMbO8njdK5AjgnZEFR1yu4XbA4Du+DtDtyfJu20R9udZF5Us94OusVygaVFDPoRmfR7rKFMMnJUGPCmCQ2UBAoLxptcKV+HghosOBOo1NvTqZ+Ed80HmlRl4TgAcNd0rb+FNlKuYY/RdYPnb5uUNl4AYvZaphIt9mTvmO2P9VKONfS5XDsepkMq0B11e7HlxWi9z8jwcsI4xhLEQTB/10r/BbvpA3dmB/h9nIB9a4aTRY1O2JW3/4qNoU7d30v/chW3trFKuygPqvsYwkiSjInmTL4QxjCN4UZYzW7VdFX1xe+lG5+XIYWwCzoQUGwhkCNsGb8pvk/W+Ihrgxs4cQ7qCGpew/K8z/okSCoUjufOnK1BQGwc4etYntbuSQPTYsQKmiAY0/BtdN7dVtNvF26xPjwH33/U4hy5f/+EVvL3eyonUCyrWrUxs+Dpa8hwq3Jdi+MIlSyE9Q8mT8iCPTCzzvnbP6EfU2APlPHHc5x+nd+F31yayXqXaHAWpUARV5wE94qJv1n2dtGq1mhfYd2lf4RtPOj5/9Vws1Gwj2/cP/uwUcqZkimz7j/sfyw="

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:

services:
  - xvfb
  - mysql

stages:
  - test
  - name: deploy
    if: branch = master

before_script:
  - mysql -uroot -e "create user testUser identified by 'testPassword';"
script:
  - travis_retry ./travis/test.sh
  - travis_retry ./gradlew jacocoTestReport
  - travis_retry ./gradlew sonarqube
after_success:
  - bash <(cat .codecov_bash)
after_failure: ./travis/junit-errors-to-stdout.sh

jobs:
  include:
    - stage: deploy
      env: RUN_TEST_GROUP=none
      install: skip
      script:
        - ./travis/bintrayDeploy.sh

env:
  jobs:
    - RUN_TEST_GROUP=build
    - RUN_TEST_GROUP=default
    - RUN_TEST_GROUP=group1
    - RUN_TEST_GROUP=coverage
  global:
    - secure: U72nmzXq7kXcIabiwvrTF+WkNFQxov2ACd8oPxWSHsyzRsfVJN42vT7gS3dLbH5G5claXG2p+rur4ueVffzYSwJ8B9OP6gTB8sNJnGr9zyxni4OJchyKqOYuj+UBpEQC/7qXKMCKnuJndsf1OvndDh/V1SH0DSSUuA6mDtgO/eM=
    - secure: WiK7tyFV68xdkIfUlWreUHgEGGjaCBd73O4SbjE9AsbqqF7D+Iu8iRo1OhKQj+6eajUH9Eoev9rVN74FQgUfeNzrOkYsgDysXmyZ7+UxFokijFcATJmIBompA3dySGU2qXeKbJMNuUjXgrRIludaV6h2ahL6Fji42cgK4I3s2qs=

jdk:
  - openjdk8
